README.md
src/main/scala/com/amazon/deequ/examples/DataProfilingExample.scala
src/main/scala/com/amazon/deequ/examples/data_profiling_example.md
src/test/scala/com/amazon/deequ/examples/ExamplesTest.scala

Add markdown documention for the data profiling example

---

src/main/scala/com/amazon/deequ/anomalydetection/seasonal/HoltWinters.scala
src/test/scala/com/amazon/deequ/anomalydetection/seasonal/HoltWintersTest.scala

Adds additive HW's method for anomaly detection including model selection on the data before the detection interval. The implementation is based on https://otexts.org/fpp2/holt-winters.html. The detector uses the standard deviation of the forecasting residuals to flag anomalies.

Additive Holt-Winters for anomaly detection

---

pom.xml
src/main/scala/com/amazon/deequ/VerificationSuite.scala
src/main/scala/com/amazon/deequ/analyzers/applicability/Applicability.scala
src/main/scala/com/amazon/deequ/constraints/AnalysisBasedConstraint.scala
src/main/scala/com/amazon/deequ/constraints/Constraint.scala
src/test/scala/com/amazon/deequ/VerificationSuiteTest.scala
src/test/scala/com/amazon/deequ/checks/ApplicabilityTest.scala
src/test/scala/com/amazon/deequ/constraints/AnalysisBasedConstraintTest.scala
src/test/scala/com/amazon/deequ/constraints/ConstraintsTest.scala

* each `ConstraintResult` in `CheckResult` is now linked to the metric that the constraint evaluation was based on
* the result of `Applicability.isApplicable(check)` now contains all constraints and their applicabilities
* adds *scoverage* with optional code coverage requirements, currently we are at a method coverage of 81% (run with `mvn scoverage:report`, https://github.com/scoverage/scoverage-maven-plugin)
* test for constraint assertions that throw exceptions

more detailed Applicability results / add metric to ConstraintResult / scoverage

---

src/main/scala/com/amazon/deequ/analyzers/Mean.scala
src/test/scala/com/amazon/deequ/analyzers/AnalyzerTests.scala

*Description of changes:* The mean was calculated in a wrong way when filtering the result set with a where-clause. Fixed that calculation and wrote a test for it. 

Fix mean calculation

---

src/main/scala/com/amazon/deequ/analyzers/applicability/Applicability.scala
src/test/scala/com/amazon/deequ/checks/ApplicabilityTest.scala

In the current, applicability checks, Deequ has a bug in generating random number for decimals. If the decimal has low precision we accidentally generate a column of nulls (as the random numbers fall outside of the range of the decimal), which causes the applicability check to crash.
This PR fixes the issue by generating decimals appropriately corresponding to the specified scale and precision. 

Fix random value generation for decimals during applicability checks

---

src/main/scala/com/amazon/deequ/checks/Check.scala
src/test/scala/com/amazon/deequ/checks/CheckTest.scala

Right operand was wrongly constructed based on the "includeLowerBound" flag rather than the "includeUpperBound" flag.

Fixes bug in right operand synthesis in "isContainedIn" check

---

.gitignore
src/main/scala/com/amazon/deequ/checks/Check.scala
src/main/scala/com/amazon/deequ/suggestions/rules/CategoricalRangeRule.scala
src/main/scala/com/amazon/deequ/suggestions/rules/FractionalCategoricalRangeRule.scala
src/test/scala/com/amazon/deequ/checks/CheckTest.scala

https://github.com/awslabs/deequ/issues/84
This PR properly escapes column names in generated Spark SQL code.
Currently, when executing a `isContainedIn` `Check` on any `DataFrame` that contains any column whose name contains any characters that make up any reserved keyword in Spark SQL will cause a runtime failure. Digging into it, the runtime failure will show the root cause is a Spark SQL syntax error (specifically a `org.apache.spark.sql.catalyst.parser.ParseException`) due to incorrectly parsing the column name. 
E.g. if the column name starts with `[`, then the exception will read as:
```
org.apache.spark.sql.catalyst.parser.ParseException:
extraneous input '[' expecting ...
```
The fix for this bug is to wrap all bare column names …

Bugfix: Escape Column Name in Generated Spark SQL

---

src/main/scala/com/amazon/deequ/analyzers/catalyst/AttributeReferenceCreation.java

In Spark 2.4 [[Spark-19602]](https://github.com/apache/spark/commit/b4bf8be549afa51e931e48dd79ddd9480f567b13) the signature for `AttributeReference` has changed (`qualifier` argument changed from `Option[String]` to `Seq[String]`), causing an `IllegalArgumentException` for some of our analyzers (`ApproxCountDistinct`) when used in conjunction with Spark 2.4. This PR adds a condition on the argument type (via reflection) for `AttributeReference`, in order to distinguish behavior for Spark 2.4 from previous versions.
Successfully tested against Spark 2.2, Spark 2.3, and Spark 2.4.

Adapts AttributeReference call to changes made in Spark 2.4

---

src/main/scala/com/amazon/deequ/profiles/ColumnProfiler.scala
src/test/scala/com/amazon/deequ/profiles/ColumnProfilerRunnerTest.scala
src/test/scala/com/amazon/deequ/profiles/ColumnProfilerTest.scala
src/test/scala/com/amazon/deequ/suggestions/ConstraintSuggestionRunnerTest.scala

Fix for issue: https://github.com/awslabs/deequ/issues/95
Description of changes:
Histogram analysis for column profiling was limited to boolean and string columns. However, it is possible to have categorical data with numerical values (ex 1 indicating male and 2 indicating female). Made changes to allow histogram analysis for columns with short, long, double, float, and integer data types

Enable column profile histogram analysis for columns of numeric types

---

src/main/scala/com/amazon/deequ/checks/Check.scala
src/test/scala/com/amazon/deequ/checks/CheckTest.scala
src/test/scala/com/amazon/deequ/utils/FixtureSupport.scala

Description of changes:
I want to use some of the convenience constraints, but with an assertion threshold.
I added a assertion param to the following check constraints:
- isPositive
- isNotNegative
- isLessThanOrEqualTo
- isLessThan
- isGreaterThanOrEqualTo
- isGreaterThan

Add assertion param to convenience constraints

---

src/test/scala/com/amazon/deequ/SparkContextSpec.scala

The test suite took 7 minutes and 7 seconds to run on my machine with `mvn test`.  I set the spark shuffle partitions to one and this sped up the test suite 68% (only takes 2 minutes & 18 seconds on my machine now).
I've seen similar performance improvements in test suite runtimes on other projects.
Thanks for creating this project :)

Set the Spark shuffle partitions to one make the test suite run 68 percent faster

---

src/test/scala/com/amazon/deequ/SparkContextSpec.scala

We reduced the number of shuffle partitions to accelerate the tests. He should however set it to at least two, as there might be some concurrency issues that we only observe with more than one partition. A setting of 2 still accelerates the tests very much though.

Adding parallelism to tests again

---

src/main/scala/com/amazon/deequ/suggestions/ConstraintSuggestionRunBuilder.scala

The `overwritePreviousFiles` function is not working properly. So whatever the parameter is, the `overwritePreviousFiles` will return back `false`.
Simple change : `overwriteOutputFiles = overwriteFiles` instead of `overwriteOutputFiles = overwriteOutputFiles `.

make the overwritePreviousFiles working

---

src/main/scala/com/amazon/deequ/repository/AnalysisResult.scala
src/main/scala/com/amazon/deequ/repository/AnalysisResultSerde.scala

Currently there is no way to implement a custom metrics repository as the `AnalysisResult` class is private to deequ. This is the return type of `get()` in the `MetricsRepositoryMultipleResultsLoader` trait, therefore there is no way to actually implement this trait.
There is also no way to serialise this result object so it can be stored in a custom way.
This PR lifts the private restriction on both the `AnalysisResult` class and it's corresponding serialisation object.

Lift the private package restriction on analysis result and corresposing serde object

---

src/main/scala/com/amazon/deequ/analyzers/Analyzer.scala
src/main/scala/com/amazon/deequ/analyzers/MaxLength.scala
src/main/scala/com/amazon/deequ/analyzers/MinLength.scala
src/main/scala/com/amazon/deequ/analyzers/StateProvider.scala
src/main/scala/com/amazon/deequ/checks/Check.scala
src/main/scala/com/amazon/deequ/constraints/Constraint.scala
src/test/scala/com/amazon/deequ/analyzers/AnalysisTest.scala
src/test/scala/com/amazon/deequ/analyzers/AnalyzerTests.scala
src/test/scala/com/amazon/deequ/analyzers/NullHandlingTests.scala
src/test/scala/com/amazon/deequ/analyzers/StateProviderTest.scala
src/test/scala/com/amazon/deequ/checks/CheckTest.scala
src/test/scala/com/amazon/deequ/constraints/ConstraintsTest.scala
src/test/scala/com/amazon/deequ/utils/FixtureSupport.scala

#45
Started adding min max length analyzer, but didn't have time to complete it.
@sscdotopen and @patchrick843 requested this work in progress pr to figure out what needs to be done still

WIP - Enhancement/min max length analyzer

---

README.md
src/main/scala/com/amazon/deequ/examples/BasicExample.scala
src/main/scala/com/amazon/deequ/examples/DataProfilingExample.scala
src/main/scala/com/amazon/deequ/examples/IncrementalMetricsExample.scala
src/main/scala/com/amazon/deequ/examples/MetricsRepositoryExample.scala
src/main/scala/com/amazon/deequ/examples/UpdateMetricsOnPartitionedDataExample.scala
src/main/scala/com/amazon/deequ/examples/algebraic_states_example.md
src/main/scala/com/amazon/deequ/examples/anomaly_detection_example.md
src/main/scala/com/amazon/deequ/examples/constraint_suggestion_example.md
src/main/scala/com/amazon/deequ/examples/data_profiling_example.md
src/main/scala/com/amazon/deequ/examples/entities.scala
src/main/scala/com/amazon/deequ/examples/metrics_repository_example.md

Issue #125 
renaming of attributes in ```examples/``` files ,
```
'name' -> 'productName',
'count' -> 'totalNumber'
```
ambiguous attribute names in the context of the example file

Fixed example files

---

src/main/scala/com/amazon/deequ/VerificationRunBuilder.scala
src/test/scala/com/amazon/deequ/VerificationSuiteTest.scala
src/test/scala/com/amazon/deequ/analyzers/PartitionedTableIntegrationTest.scala

*Issue #, if available:* #92 
*Description of changes:*   
Adds two methods to [`VerificationRunBuilder`](https://github.com/awslabs/deequ/blob/e333f4b507323cdd84ae084cc711eae1bab7a590/src/main/scala/com/amazon/deequ/VerificationRunBuilder.scala#L28) to allow saving and aggregation of states. 
Currently the only way to do this with the [`VerificationSuite`](https://github.com/awslabs/deequ/blob/e333f4b507323cdd84ae084cc711eae1bab7a590/src/main/scala/com/amazon/deequ/VerificationSuite.scala#L42) is by using the deprecated [`run`](https://github.com/awslabs/deequ/blob/e333f4b507323cdd84ae084cc711eae1bab7a590/src/main/scala/com/amazon/deequ/VerificationSuite.scala#L67) method.
This would allow users to use the stateful metrics computation features of deequ without relying on deprecated …

WIP - adds state provider support to VerificationRunBuilder (#92)

---

src/main/scala/com/amazon/deequ/suggestions/ConstraintSuggestionResult.scala
src/main/scala/com/amazon/deequ/suggestions/ConstraintSuggestionRunner.scala
src/test/scala/com/amazon/deequ/suggestions/ConstraintSuggestionsIntegrationTest.scala

We should report the number of records used for profiling during constraint suggestion.

Report number of records used for profiling during constraint suggestion

---

src/main/scala/com/amazon/deequ/analyzers/Distance.scala
src/main/scala/com/amazon/deequ/analyzers/QuantileNonSample.scala
src/test/scala/com/amazon/deequ/KLL/KLLDistanceTest.scala
src/test/scala/com/amazon/deequ/KLL/KLLProbTest.scala
src/test/scala/com/amazon/deequ/KLL/KLLProfileTest.scala

The unit tests for KLL Sketches, which tests the probability error, are yet to be implemented.
Add distance comparison functions for numerical & categorical profiles.

Add numerical & categorical distance comparison

---

src/main/scala/com/amazon/deequ/analyzers/ApproxQuantile.scala
src/main/scala/com/amazon/deequ/metrics/Metric.scala
src/test/scala/com/amazon/deequ/analyzers/AnalysisTest.scala

*Issue:*
#168
- Quantile calculated was not represented on ApproxQuantile metric, making it confusing on the results. Quantile has been added.
- Metric name was not added on ApproxQuantiles when they where flattened. "Name" literal has been replaced by the metric name

deequ-168: Improve approxQuantile metrics instance description

---

src/main/scala/com/amazon/deequ/analyzers/DataType.scala
src/main/scala/com/amazon/deequ/profiles/ColumnProfiler.scala
src/main/scala/com/amazon/deequ/profiles/ColumnProfilerRunBuilder.scala
src/main/scala/com/amazon/deequ/profiles/ColumnProfilerRunner.scala
src/main/scala/com/amazon/deequ/suggestions/ConstraintSuggestionRunBuilder.scala
src/main/scala/com/amazon/deequ/suggestions/ConstraintSuggestionRunner.scala
src/test/scala/com/amazon/deequ/profiles/ColumnProfilerTest.scala

This pull request is mainly focusing on respecting the data types customers set in baseline constraints. One simple example would be that there's one column named "Zip Code", customers would like it to have dataType "String", but if the dataType in df.schema is StringType, then Deequ would infer the dataType to be "Integral" and run a numerical analysis. After this change, if a baseline dataType is given for a column, it will be respected. I am making the parameter to be optional so that it won't affect the cases when a baseline is not given.

Set predefined data type to respect customer's customized data type in baseline

---

pom.xml
src/main/scala/com/amazon/deequ/analyzers/GroupingAnalyzers.scala
src/test/scala/com/amazon/deequ/analyzers/AnalyzerTests.scala
src/test/scala/com/amazon/deequ/analyzers/IncrementalAnalyzerTest.scala
src/test/scala/com/amazon/deequ/analyzers/NullHandlingTests.scala
src/test/scala/com/amazon/deequ/analyzers/UniquenessTest.scala
src/test/scala/com/amazon/deequ/checks/CheckTest.scala

* Fixes computation of uniqueness, distinctness, etc for datasets with null values, as a response to #178 
* Bumps version number to 1.1 to indicate that some existing tests might break due to the corrected semantics

Fix computation of uniqueness, distinctness, etc. for datasets with null values

---

src/main/scala/com/amazon/deequ/analyzers/Histogram.scala
src/main/scala/com/amazon/deequ/examples/ExampleUtils.scala
src/main/scala/com/amazon/deequ/examples/entities.scala
src/test/scala/com/amazon/deequ/analyzers/StateAggregationIntegrationTest.scala

This fixes a wrong column name in Histogram as outlined in https://github.com/awslabs/deequ/issues/189

Adjusted name for count column in Histogram

---

src/test/scala/com/amazon/deequ/profiles/ColumnProfilerTest.scala
test-data/README.md
test-data/titanic.csv

*Issue #22
New unit test for column profiling based on external file with titanic dataset.
It doesn't fix any problems but I think it can be useful as simple example how to create this kind of tests based on the external datasets. It shows where to put the dataset, how to read it and how to add information about its source. Also it has 891 rows so is bigger than other smaller test cases.
The only not exact value is number of unique values in 'PassengerId` column. should be 891 but is approximated as 887. So probably it is ok.

Unit test based on titanic dataset for column profiling.

---

src/main/scala/com/amazon/deequ/checks/Check.scala
src/main/scala/com/amazon/deequ/checks/ColumnCondition.scala
src/test/scala/com/amazon/deequ/checks/CheckTest.scala
src/test/scala/com/amazon/deequ/checks/ColumnConditionTest.scala

#220 
Adds isAnyNotNull ColumnCondition which allows checking for if data exist in a set of columns. Example use case would be mutually exclusive data in a denormalized table populated with nulls for the column without data.

Determine any data completeness over a set of columns

---

src/main/scala/com/amazon/deequ/VerificationSuite.scala
src/main/scala/com/amazon/deequ/analyzers/runners/AnalysisRunner.scala
src/test/scala/com/amazon/deequ/VerificationResultTest.scala
src/test/scala/com/amazon/deequ/VerificationSuiteTest.scala
src/test/scala/com/amazon/deequ/analyzers/AnalysisTest.scala
src/test/scala/com/amazon/deequ/analyzers/runners/AnalysisRunnerTests.scala

*Issue #, if available:* #227 
For AnalysisRunner, now if user gives duplicates analyzers, then it will throw error with list of analyzers which were causing them
In VerificationSuite, as discussed in issue there is case when user can add "Checks" + "RequiredAnalyzer" because of which it creates analyzers list with duplicates and we can't stop it from user side so we take distinct values of it
In AnalysisTest, there was one test case which will fail because of this change hence removed and added new one

Fix duplicate analyzer for AnalysisRunner

---

src/main/scala/com/amazon/deequ/analyzers/Analyzer.scala
src/test/scala/com/amazon/deequ/analyzers/AnalysisTest.scala

issue 236
It supports spark sql's case sensitivity, spark.sql.caseSensitive

deequ-236 Supporting spark.sql.caseSensitive property

---

src/main/scala/com/amazon/deequ/examples/constraint_suggestion_example.md
src/main/scala/com/amazon/deequ/examples/data_profiling_example.md

This PR updates the timed example documentation to actual example scripts.
update documents:
- `data_profiling_example.md` (sync to [`DataProfilingExample.scala`](https://github.com/awslabs/deequ/blob/d9640b5b56c7104cbf6954abc4a85f142428e94f/src/main/scala/com/amazon/deequ/examples/DataProfilingExample.scala))
- `constraint_suggestion_example.md` (sync to [`ConstraintSuggestionExample.scala`](https://github.com/awslabs/deequ/blob/d9640b5b56c7104cbf6954abc4a85f142428e94f/src/main/scala/com/amazon/deequ/examples/ConstraintSuggestionExample.scala#L1))
The main changes are two below:
- `count` -> `totalNumber`
- fix ambiguous `spark` variable
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache …

update example documentation to actual example script:

---

src/main/scala/com/amazon/deequ/VerificationRunBuilder.scala
src/main/scala/com/amazon/deequ/examples/KLLExample.scala
src/main/scala/com/amazon/deequ/examples/algebraic_states_example.md

I did three small udpates:
1. rename `productName` to `manufacturerName` in [albebraic_states_example](https://github.com/awslabs/deequ/blob/22bcff91d6bd8abe7203f696e0fa9d8d0defef57/src/main/scala/com/amazon/deequ/examples/algebraic_states_example.md) doc
It uses `productName` field, but in [its executable](https://github.com/awslabs/deequ/blob/47b300a230213b20ce4e533cf3165c285912f570/src/main/scala/com/amazon/deequ/examples/entities.scala#L29), there is no field `productName` but `manufactureName` is. And so I made them consistent.
2. fix typo in [VerificationRunBuilder.scala](https://github.com/awslabs/deequ/blob/22bcff91d6bd8abe7203f696e0fa9d8d0defef57/src/main/scala/com/amazon/deequ/VerificationRunBuilder.scala)
3. fix …

update documentation, example:

---

src/main/scala/com/amazon/deequ/suggestions/rules/CategoricalRangeRule.scala
src/main/scala/com/amazon/deequ/suggestions/rules/FractionalCategoricalRangeRule.scala
src/test/scala/com/amazon/deequ/suggestions/rules/ConstraintRulesTest.scala

Currently `(Fractional)CategoricalRangeRule` is only applied to `String`-valued columns (because of [this filtering](https://github.com/awslabs/deequ/blob/47b300a230213b20ce4e533cf3165c285912f570/src/main/scala/com/amazon/deequ/suggestions/rules/CategoricalRangeRule.scala#L30)), as such deequ doesn't suggest any categorical rule for columns whose values are numeric.
But as far as I can tell, read-world data so often have "categorical" columns whose values are actually numeric (mostly integer), e.g. the famous [tatanic](https://www.kaggle.com/c/titanic/data) data also has `Survived` column whose values are `0` or `1`, while it's obviously supposed to be considered as "categorical" (or rather flag) column.
I believe suggesting …

suggest `CategoricalRangeRule` for integer columns

---

src/main/scala/com/amazon/deequ/analyzers/catalyst/StatefulDataType.scala
src/test/scala/com/amazon/deequ/DatatypeSuggestionTest.scala
src/test/scala/com/amazon/deequ/utils/FixtureSupport.scala

Fixes #301 
Changed the REGEX for Integral and Fractional datatype.
This is because if a column has all values as empty string ("") then it is suggested as a integral column with a numeric column profile while it should not be.

Fixes #301: Datatype REGEX fix for column profiler;

---

src/main/scala/com/amazon/deequ/analyzers/catalyst/StatefulDataType.scala
src/main/scala/com/amazon/deequ/checks/Check.scala
src/test/scala/com/amazon/deequ/checks/CheckTest.scala

really fixes #276 
- it turns out we need to handle scientific notations in `isNonNegative` and `isPositive` checks as well; this time we need to use `cast(col as decimal(n, n)` to eliminate scientific notations before doing checks
- built on top of #311 (you can see the actual diff from #311 in https://github.com/awslabs/deequ/pull/312/commits/7539fd21213bb8fcffd01a6948bfbc84500766e8)
I'm okay with either of 1.) merge #311 first, and then merge this branch into `master` after rebasing or such, 2.) merge this as is and close #311

correctly handle scientific notations in `isNonNegative`/`isPositive` checks as well

---

src/main/scala/com/amazon/deequ/VerificationSuite.scala
src/test/scala/com/amazon/deequ/VerificationSuiteTest.scala

… checks #316
*Issue #316*
*use distinct analyzers to enable using same analyzers for anomaly and checks:*

Enable using same analyzers for anomaly and CHECK constraints

---

Makefile
README.md
pom.xml

*Issue #, if available: https://github.com/awslabs/deequ/issues/353, https://github.com/awslabs/deequ/issues/349*
This PR
- drastically simplifies the pom.xml by removing most profiles. Releases now require more manual work to set the right scala and spark versions, but this change should make the releases usable again. The Makefile is also updated to remove the logic related to the (now removed) pom.xml build profiles.
- updates the readme to point to a working release. 
I performed releases for Spark 2.2.x to 3.0.x that include the changes from this PR. The releases are called `1.2.2-spark-..` and they should become available on maven over the next days ([Link to maven repository](https://mvnrepository.com/artifact/com.amazon.deequ/deequ)).
A couple of work items should be completed …

Update release process and point README to a working release

---

README.md

Travis-CI is moving domains from .org to .com.  When you go to the older .org domain it recommends redirecting and updating links.

travis-ci.org to travis-ci.com link

---

pom.xml
src/main/scala/com/amazon/deequ/analyzers/catalyst/StatefulCorrelation.scala
src/main/scala/com/amazon/deequ/analyzers/catalyst/StatefulStdDevPop.scala

AFAIU the only requirement is update for <https://github.com/apache/spark/pull/29983>.
In order to be consistent with the previous behavior and pass the
existing test suite, this PR is essentially equavalent to setting
`spark.sql.legacy.statisticalAggregate` to `true`.
Now the code is incompatible with spark-2.x or spark-3.0, and so I'd
like to recommend only supporting spark 3.1 and higher and scala 2.12
from now on.

update to spark3.1

---

src/main/scala/com/amazon/deequ/analyzers/PatternMatch.scala
src/test/scala/com/amazon/deequ/analyzers/AnalyzerTests.scala

The PatternMatch hashCode differs for the same class parameters because Regex parameter compares by reference other than the pattern value.
A possible problem this causing is getting PatternMatch metrics from AnalyzerContext map will return nothing if the PatternMatch object does not reference equal.

Fix PatternMatch hashCode bug

---

pom.xml
src/main/scala/com/amazon/deequ/analyzers/catalyst/StatefulApproxQuantile.scala
src/main/scala/com/amazon/deequ/analyzers/catalyst/StatefulCorrelation.scala
src/test/scala/com/amazon/deequ/SparkContextSpec.scala

https://github.com/awslabs/deequ/issues/380
- fix hasCorrelation Check fail
- fix failed tests when verifying number of submitted jobs due to AQE is enabled by default from Spark 3.2
- fix `scala.reflect` related error
- format scala files to pass scalastyle check
`mvn clean build` has been executed successfully on my local PC.

Upgrade to spark 3.2

---

pom.xml
src/main/scala/com/amazon/deequ/analyzers/Distance.scala
src/test/scala/com/amazon/deequ/KLL/KLLDistanceTest.scala

The distance method used in `src/main/scala/com/amazon/deequ/analyzers/Distance.scala` applies the Kolmogorov–Smirnov(KS) test to numerical and categorical variables. As the KS test is mostly [suited](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2996580/) for numerical variables this PR adds the chi-square test method that can be optionally used with categorical variables. The function signature of `categoricalDistance`  remains unchanged and still applies the KS test as default method.
Modified files:
`src/main/scala/com/amazon/deequ/analyzers/Distance.scala` : added chi-square method
`src/test/scala/com/amazon/deequ/KLL/KLLDistanceTest.scala` : added tests for chi-square method
`pom.xml` : added dependency to spark-mllib
By submitting this pull request, I …

Adding chi-square distance method for categorical variables

---

deequ-scalastyle.xml
src/main/scala/com/amazon/deequ/VerificationResult.scala
src/main/scala/com/amazon/deequ/analyzers/Analyzer.scala
src/main/scala/com/amazon/deequ/analyzers/Completeness.scala
src/main/scala/com/amazon/deequ/analyzers/MaxLength.scala
src/main/scala/com/amazon/deequ/analyzers/Maximum.scala
src/main/scala/com/amazon/deequ/analyzers/catalyst/DeequFunctions.scala
src/main/scala/com/amazon/deequ/analyzers/runners/AnalysisRunner.scala
src/main/scala/com/amazon/deequ/checks/Check.scala
src/main/scala/com/amazon/deequ/constraints/Constraint.scala
src/main/scala/com/amazon/deequ/metrics/Metric.scala
src/main/scala/com/amazon/deequ/repository/AnalysisResultSerde.scala
src/test/scala/com/amazon/deequ/VerificationSuiteTest.scala
src/test/scala/com/amazon/deequ/analyzers/AnalysisTest.scala
src/test/scala/com/amazon/deequ/analyzers/AnalyzerTests.scala
src/test/scala/com/amazon/deequ/analyzers/CompletenessTest.scala
src/test/scala/com/amazon/deequ/analyzers/MaxLengthTest.scala
src/test/scala/com/amazon/deequ/analyzers/NullHandlingTests.scala
src/test/scala/com/amazon/deequ/analyzers/StateProviderTest.scala
src/test/scala/com/amazon/deequ/checks/CheckTest.scala
src/test/scala/com/amazon/deequ/suggestions/ConstraintSuggestionRunnerTest.scala
src/test/scala/com/amazon/deequ/utils/FixtureSupport.scala

N/A
This is an early version of the row-level results feature. I have enabled row-level results in three constraints: `IsComplete`, `HasCompleteness`, and `MaxLength`.
This requires the definition and change of certain classes defined in Deequ both to expose information previously not available, and to allow distinguishing between different analyzers' results.

Feature: Row Level Results

---

pom.xml

Updates the url in `pom.xml` to https://aws.oss.sonatype.org/ to publish to the correct maven repository.
Change the tag `<autoReleaseAfterClose>` to false, which allows us the review the release after the validation passes. (https://help.sonatype.com/repomanager2/staging-releases/configuring-your-project-for-deployment)

Update pom.xml to publish to https://aws.oss.sonatype.org/

---

src/main/scala/com/amazon/deequ/comparison/ReferentialIntegrity.scala
src/test/scala/com/amazon/deequ/comparison/ReferentialIntegrityTest.scala

- The change involves updating the API to accept a list of columns for both the primary and reference dataframes.
- This is still an experimental utility, hence we are changing the API.
- Added tests to verify the updated behavior.

Updated Referential Integrity to support multiple columns

---

src/main/scala/com/amazon/deequ/comparison/ReferentialIntegrity.scala
src/test/scala/com/amazon/deequ/comparison/ReferentialIntegrityTest.scala

- No associated issue. This is a WIP experimental utility.
- The provided primary data frame will have a column added to it to indicate a true/false value.
- The value will be true if the values of the provided columns for that row exist in the reference dataframe. Otherwise, the value will be false.
- Added various tests, including tests for nested columns.
- Refactored the parameter validation from the regular row level check, so that the same validation can be done in the new function as well.
- Updated scaladoc of the two APIs.

New API added to referential integrity to allow for row level annotation

---

src/main/scala/com/amazon/deequ/comparison/ComparisonBase.scala
src/main/scala/com/amazon/deequ/comparison/DataSynchronization.scala
src/main/scala/com/amazon/deequ/comparison/ReferentialIntegrity.scala
src/test/scala/com/amazon/deequ/comparison/DataSynchronizationTest.scala

- We hash the non key columns from both dataframes and store them as additional columns in each dataframe.
- We use the key columns map and the hash columns to join the data frames.
- We then check if the key columns and the hash column from the second dataframe are not null. If not null, then the row matches, otherwise it does not.
- Added tests to verify the behavior for non-nested and nested data.

[Experimental] Added a function to the Data Synchronization utility for annotating the dataframe with row level results

---

src/main/scala/com/amazon/deequ/analyzers/Distance.scala
src/test/scala/com/amazon/deequ/KLL/KLLDistanceTest.scala

Adds the population stability index (PSI) to distance methods for numerical features.
Population stability index (PSI) is a statistical measure with a basis in information theory that quantifies the difference between one probability distribution from a reference probability distribution.

Add population stability index (PSI) to distance methods

---

src/main/scala/com/amazon/deequ/analyzers/Distance.scala
src/test/scala/com/amazon/deequ/KLL/KLLDistanceTest.scala

Chi-square test is only be conducted when the key size of the expected dataset is greater equal the minium.
Additional tests have been added.

Fix chi-square test conditions

---

src/main/scala/com/amazon/deequ/comparison/DataSynchronization.scala
src/test/scala/com/amazon/deequ/comparison/DataSynchronizationTest.scala

The error thrown by this rule when the datasets are not comparable is not verbose enough, leading to confusion about the reasons why the comparison did not happen.

Improve message wording for dataset comparison

---

src/main/scala/com/amazon/deequ/suggestions/ConstraintSuggestion.scala
src/main/scala/com/amazon/deequ/suggestions/rules/CategoricalRangeRule.scala
src/main/scala/com/amazon/deequ/suggestions/rules/CompleteIfCompleteRule.scala
src/main/scala/com/amazon/deequ/suggestions/rules/ConstraintRule.scala
src/main/scala/com/amazon/deequ/suggestions/rules/FractionalCategoricalRangeRule.scala
src/main/scala/com/amazon/deequ/suggestions/rules/HasMax.scala
src/main/scala/com/amazon/deequ/suggestions/rules/HasMaxLength.scala
src/main/scala/com/amazon/deequ/suggestions/rules/HasMean.scala
src/main/scala/com/amazon/deequ/suggestions/rules/HasMin.scala
src/main/scala/com/amazon/deequ/suggestions/rules/HasMinLength.scala
src/main/scala/com/amazon/deequ/suggestions/rules/HasStandardDeviation.scala
src/main/scala/com/amazon/deequ/suggestions/rules/NonNegativeNumbersRule.scala
src/main/scala/com/amazon/deequ/suggestions/rules/RetainCompletenessRule.scala
src/main/scala/com/amazon/deequ/suggestions/rules/RetainTypeRule.scala
src/main/scala/com/amazon/deequ/suggestions/rules/UniqueIfApproximatelyUniqueRule.scala
src/test/scala/com/amazon/deequ/suggestions/ConstraintSuggestionsIntegrationTest.scala

- The new class contains an additional field, which can be used to store a value associated with the constraint.
- This is useful for the categorical range rule, to store the categories. This way, the values can be extracted without needing to parse the constraint code which is stored as a string.

Updated the Categorical range constraint suggestions to use a new class called ConstraintSuggestionWithValue

---

src/main/scala/com/amazon/deequ/analyzers/Analyzer.scala
src/main/scala/com/amazon/deequ/analyzers/MaxLength.scala
src/main/scala/com/amazon/deequ/analyzers/MinLength.scala
src/test/scala/com/amazon/deequ/profiles/ColumnProfilerTest.scala
src/test/scala/com/amazon/deequ/utils/FixtureSupport.scala

*Issue*
- The column profiling for min/max lengths for a string column is not working when the column name has a space in it.
- Replaced Spark SQL isNull check with Spark Scala based DSL
- This is to ensure columns with spaces in their names get their names escaped correctly in the where condition.
- Added a test to verify.

Replace Spark SQL isNull check with Spark Scala based DSL

---

src/main/scala/com/amazon/deequ/analyzers/Histogram.scala
src/main/scala/com/amazon/deequ/repository/AnalysisResultSerde.scala
src/test/scala/com/amazon/deequ/analyzers/AnalyzerTests.scala
src/test/scala/com/amazon/deequ/analyzers/runners/AnalyzerContextTest.scala
src/test/scala/com/amazon/deequ/repository/AnalysisResultSerdeTest.scala

NA. Kind of close to #381 
- Histogram analyzer changes
-  Provide a way to calculate histogram values using different aggregate functions (sum).
- Add aggregateColumn - a column castable to Long. Aggregate function is applied to this column
- Histogram serialization changes
- Add aggregateFunction property ("count" is default in case of missing property)
- Add aggregateColumn property
In addition to
``` 
select(col(column).cast(StringType)).groupBy(column).count()
```
provide a way get histogram values
```
select(col(column).cast(StringType), col(aggregateColumn.get).cast(LongType)).groupBy(column).sum(aggregateColumn.get)
```
WIP. Please take a look at the changes. I'll add more tests, docs and validation logic if you think that these …

Alternative aggregate functions to calculate histogram values.

---

src/main/scala/com/amazon/deequ/checks/Check.scala
src/main/scala/com/amazon/deequ/constraints/Constraint.scala
src/test/scala/com/amazon/deequ/constraints/AnalysisBasedConstraintTest.scala

Due to our typing system, it is always possible to create an Analyzer, but converting that into a generic Constraint and generic Check is impossible. 
Instead, give callers the option to convert an Analyzer into a Check with these helper functions. This enables reuse of Analyzers - you can use an Analyzer directly, or convert it to a Check by assigning it a severity and assertion.

Allow all DQ constraints to be generated from an Analyzer

---

pom.xml
src/main/scala/com/amazon/deequ/analyzers/CustomSql.scala
src/main/scala/com/amazon/deequ/analyzers/Size.scala
src/test/scala/com/amazon/deequ/analyzers/CustomSqlTest.scala

- Run scalastyle before tests
- New analyzer to evaluate a SQL statement that returns a boolean value
- Introduce a new Analyzer, CustomSql, that takes a SQL statement that returns a Double value and returns that 
value as a state

Custom SQL Analyzer

---

src/main/scala/com/amazon/deequ/analyzers/CustomSql.scala
src/test/scala/com/amazon/deequ/analyzers/CustomSqlTest.scala

If the SQL statement has an error, return a failed state from the CustomSql analyzer

Fail when CustomSql has syntax errors

---

src/test/scala/com/amazon/deequ/analyzers/CustomSqlTest.scala

CustomSQL Analyzer test was failing with Spark 3.3.0 with the error:
`org.scalatest.exceptions.TestFailedException: "Column 'foo' does not exist. Did you mean one of the following? [primary.Country, primary.Address Line 1, primary.Address Line 2, primary.Address Line 3]; line 1 pos 7;`
while other versions (3.1.0, 3.4.0) fails with:
`"cannot resolve '`foo`' given input columns: [primary.Address Line 1, primary.Address Line 2, primary.Address Line 3, primary.Country]; line 1 pos 7;`
The test was checking that \`foo\` was in the exception, but for Spark 3.3.0 the error message showed 'foo' instead.
Modifying the test to pass for all versions
By submitting this pull request, I confirm that my contribution is made under the terms of the …

Fix CustomSQL test syntax

---

src/main/scala/com/amazon/deequ/comparison/DataSynchronization.scala
src/test/scala/com/amazon/deequ/comparison/DataSynchronizationTest.scala

- Prior to this change, we were doing case sensitive equality checks of non-key columns.
- This makes the utility more restrictive, as Spark does not care about the casing of column names.
- With this change, we rely on Spark to check if a column exists in the given dataframe. If Spark can find the column, we can proceed with the rest of the check.
N/A

[Data Synchronization/Matching] Delegate to Spark for checking existence of columns in the given dataframes

---

src/main/scala/com/amazon/deequ/analyzers/ExactQuantile.scala
src/main/scala/com/amazon/deequ/analyzers/StateProvider.scala
src/main/scala/com/amazon/deequ/checks/Check.scala
src/main/scala/com/amazon/deequ/constraints/Constraint.scala
src/main/scala/com/amazon/deequ/repository/AnalysisResultSerde.scala
src/test/scala/com/amazon/deequ/checks/CheckTest.scala
src/test/scala/com/amazon/deequ/repository/AnalysisResultSerdeTest.scala

Added hasExactQuantile Check. Similar to hasApproxQuantile but finds more precise quantile value.

Creation of Exact Quantile Check

---

src/main/scala/com/amazon/deequ/comparison/DataSynchronization.scala
src/test/scala/com/amazon/deequ/comparison/DataSynchronizationTest.scala

- The non existence of non key columns was resulting in a Spark SQL exception, instead of a graceful "ComparisonFailed" return value.
- In a future PR, will consolidate all the column validation logic into one single place.
*Issue #, if available:* N/A

Verify that non key columns exist in each dataset

---

pom.xml
src/main/scala/com/amazon/deequ/repository/sparktable/SparkMetricsRepository.scala
src/test/scala/com/amazon/deequ/SparkContextSpec.scala
src/test/scala/com/amazon/deequ/repository/sparktable/SparkTableMetricsRepositoryTest.scala

https://github.com/awslabs/deequ/issues/502 
An implementation of MetricsRepository using Spark tables as the data source.
Currently, DQ heavily relies on spark for processing. But to save metrics to a table like Iceberg or Hive or other spark catalog based, we don't have an implementation. With this PR, users can  save metrics to a table and read them offline as needed. 
Example usage - 
```scala
val spark = <your spark session>
val repository = new SparkTableMetricsRepository(spark, "metrics_table")
repository.save(resultKey, context)
```

MetricsRepository using Spark tables as the data source

---

src/main/scala/com/amazon/deequ/analyzers/Analyzer.scala
src/main/scala/com/amazon/deequ/analyzers/DataSynchronizationAnalyzer.scala
src/main/scala/com/amazon/deequ/analyzers/DataSynchronizationState.scala
src/main/scala/com/amazon/deequ/checks/Check.scala
src/main/scala/com/amazon/deequ/comparison/ComparisonResult.scala
src/main/scala/com/amazon/deequ/comparison/DataSynchronization.scala
src/main/scala/com/amazon/deequ/constraints/Constraint.scala
src/test/scala/com/amazon/deequ/VerificationSuiteTest.scala
src/test/scala/com/amazon/deequ/checks/CheckTest.scala
src/test/scala/com/amazon/deequ/comparison/DataSynchronizationTest.scala

*Issue, if available: #501
*Description of changes:* Adding data synchronization check to verification suite, with this change users can define `isDataSynchronized` check.
Example usage - 
```scala
val verificationResult = VerificationSuite()
.onData(data)
.addCheck(Check(CheckLevel.Error, "must have data in sync")
.isDataSynchronized(dfToCompare, Map("id" -> "id"), _ > 0.7)
.run()
```
cc: @mentekid @rdsharma26

add data synchronization test to verification Suite.

---

pom.xml
src/main/scala/com/amazon/deequ/analyzers/catalyst/StatefulHyperloglogPlus.scala

https://github.com/awslabs/deequ/issues/507
- Add Spark 3.5 support 
`mvn clean package` run successfully on my local machine. Test result is as followed:
```
Run completed in 5 minutes, 19 seconds.
Total number of tests run: 557
Suites: completed 65, aborted 0
Tests: succeeded 557, failed 0, canceled 0, ignored 0, pending 0
All tests passed.
```

Add Spark 3.5 support

---

src/test/scala/com/amazon/deequ/repository/sparktable/SparkTableMetricsRepositoryTest.scala

The SparkTableMetricRepositoryTest file was added in this PR #518.
The test `save and load to iceberg a single metric` uses the `SupportsRowLevelOperations` class which is supported from spark 3.3.
This change modifies the test so we skip it for spark versions lower than 3.3

Skip SparkTableMetricsRepositoryTest test when SupportsRowLevelOperations is not available

---

src/main/scala/com/amazon/deequ/checks/Check.scala
src/main/scala/com/amazon/deequ/constraints/Constraint.scala
src/test/scala/com/amazon/deequ/VerificationSuiteTest.scala

Follow-up PR to #532 and #535 
- Adding AnalyzerOptions to use FilteredRowOutcome for `isPrimaryKey` Check which uses the `Uniqueness` analyzer

Add analyzerOption to add filteredRowOutcome for isPrimaryKey Check

---

src/main/scala/com/amazon/deequ/analyzers/MaxLength.scala
src/main/scala/com/amazon/deequ/analyzers/MinLength.scala
src/test/scala/com/amazon/deequ/VerificationSuiteTest.scala
src/test/scala/com/amazon/deequ/checks/CheckTest.scala

- While testing, we found a bug that when using the `MaxLength` or `MinLength` analyzers with the `NullBehavior.EmptyString` analyzer option, we weren't properly emitting metrics when using a where filter. 
- This was because the `filter` was not properly applied to constructing the criterion.
- This PR fixes this issue for both `MaxLength` and `MinLength` analyzers and adds tests to verify.

Fix bug in MinLength and MaxLength when NullBehavior.EmptyString

---

src/main/scala/com/amazon/deequ/analyzers/Analyzer.scala
src/main/scala/com/amazon/deequ/analyzers/MaxLength.scala
src/main/scala/com/amazon/deequ/analyzers/Maximum.scala
src/main/scala/com/amazon/deequ/analyzers/MinLength.scala
src/main/scala/com/amazon/deequ/analyzers/Minimum.scala
src/main/scala/com/amazon/deequ/constraints/Constraint.scala
src/test/scala/com/amazon/deequ/VerificationSuiteTest.scala
src/test/scala/com/amazon/deequ/analyzers/MaxLengthTest.scala
src/test/scala/com/amazon/deequ/analyzers/MaximumTest.scala
src/test/scala/com/amazon/deequ/analyzers/MinLengthTest.scala
src/test/scala/com/amazon/deequ/utils/FixtureSupport.scala

- For certain scenarios, the filtered row behavior for MinLength and MaxLength was not working correctly.
- For example, when using both minLength and maxLength constraints in a single check, and with both using == <value> as an assertion. This was resulting in the row level outcome of the filtered rows to be false. This was because we were replacing values for filtered rows for Min to MaxValue and for Max to MinValue. But a number could not equal both at the same time.
```
val analyzerOptions = AnalyzerOptions(
nullBehavior = NullBehavior.EmptyString,
filteredRow = FilteredRowOutcome.TRUE
)
val check = new Check(CheckLevel.Error, "test-check")
.hasMinLength("Company", _ == 8, analyzerOptions = Some(analyzerOptions)).where("ID > 2")
.hasMaxLength("Company", _ == …
```

[MinLength/MaxLength] Apply filtered row behavior at the row level evaluation

---

src/main/scala/com/amazon/deequ/anomalydetection/seasonal/HoltWinters.scala
src/test/scala/com/amazon/deequ/anomalydetection/seasonal/HoltWintersTest.scala

Add Daily Season with Hourly Interval to HoltWinter: #296
Add constructor that directly take seriesPeriodicity

Anomaly Detection: Add Daily Season with Hourly Interval to HoltWinter

---

src/main/scala/com/amazon/deequ/analyzers/RatioOfSums.scala
src/main/scala/com/amazon/deequ/repository/AnalysisResultSerde.scala
src/test/scala/com/amazon/deequ/analyzers/AnalyzerTests.scala
src/test/scala/com/amazon/deequ/repository/AnalysisResultSerdeTest.scala

This PR creates a new analyzer called RatioOfSums. It aggregates and sums 2 separate columns, then divides them.
For example, imagine a baseball dataset that contains hits and total at-bats, with a row for every player in every game. If a player's batting average (total hits/total at-bats) changes by more than 0.2 in one week, an error or warning could be given. Another example is a % of total calculation in a table that has many rows with facts val1, val2, val3, total, and we want to ensure that val1's percent of the total doesn't change more than X in a given time period. 

New analyzer, RatioOfSums

---

src/main/scala/com/amazon/deequ/analyzers/ColumnCount.scala
src/main/scala/com/amazon/deequ/analyzers/CustomSql.scala
src/main/scala/com/amazon/deequ/analyzers/Size.scala
src/main/scala/com/amazon/deequ/checks/Check.scala
src/main/scala/com/amazon/deequ/constraints/Constraint.scala
src/test/scala/com/amazon/deequ/KLL/KLLDistanceTest.scala
src/test/scala/com/amazon/deequ/VerificationSuiteTest.scala
src/test/scala/com/amazon/deequ/analyzers/ColumnCountTest.scala

- **Fix flaky KLL test**
- **Move CustomSql state to CustomSql analyzer**
- **Implement new Analyzer to count columns**
This adds a dataset-scope analyzer that counts the number of columns in a dataset, and uses the analyzer in a Deequ Check

Column Count Analyzer and Check

---

pom.xml

Update breeze version to 2.1 to match with current spark-mlib 3.4 and spark-mlib 3.5 breeze dependency version. This would allow people migrating to spark 3.4+ to use anomaly detection without dependency conflict issue that is mentioned in
https://github.com/awslabs/deequ/issues/336
https://github.com/awslabs/deequ/issues/393
https://github.com/awslabs/deequ/issues/428
https://github.com/awslabs/deequ/issues/428
Also Breeze 0.13.2 has several security vulnerabilities which was solve in breeze 2.1.0

Fix Breeze dependency conflict in Anomaly Detection Spark 3.4+

---

src/main/scala/com/amazon/deequ/suggestions/rules/RetainCompletenessRule.scala
src/test/scala/com/amazon/deequ/suggestions/rules/ConstraintRulesTest.scala

Configurable RetainCompletenessRule

---

src/main/scala/com/amazon/deequ/analyzers/CustomSql.scala
src/test/scala/com/amazon/deequ/analyzers/CustomSqlTest.scala

*Issue #, if available:* N/A
*Description of changes:* 
* Allow (but do not require) specification of metric instance name in CustomSQL analyzer. 
* This will allow users to more easily distinguish success metrics produced by multiple distinct CustomSQL statements within a VerificationSuite.

Optional specification of instance name in CustomSQL analyzer metric.

---

src/main/scala/com/amazon/deequ/VerificationResult.scala

Fixes #576
Iteratively calling `withColumn` (singular) on a DataFrame causes performance issues when iterating over a large sequence of columns. (See issue for more details.) The code was iterating to add each `(name, column)` pair in a map to the DataFrame, so we can use [`withColumns`](https://spark.apache.org/docs/latest/api/scala/org/apache/spark/sql/Dataset.html#withColumns(colsMap:Map%5BString,org.apache.spark.sql.Column%5D):org.apache.spark.sql.DataFrame), which takes a `Map[String, Column]` as its parameter, as a drop-in replacement.
After running the performance test in the bug ticket, the performance is much better:
```
Gathering row-level results
51 columns in row level results
Duration was 67ms
Gathering row-level results
101 columns in row level results
Duration was 53ms …
```

Fix performance of building row-level results

---

src/main/scala/com/amazon/deequ/VerificationResult.scala

Fixes a bug introduced in #577.
[`withColumns`](https://spark.apache.org/docs/latest/api/scala/org/apache/spark/sql/Dataset.html#withColumns(colsMap:Map[String,org.apache.spark.sql.Column]):org.apache.spark.sql.DataFrame) was introduced in Spark 3.3, so it won't work for Deequ's <3.3 builds. This switches the implementation to instead use `select`, which is what's recommended in the note in [`withColumn`](https://spark.apache.org/docs/latest/api/scala/org/apache/spark/sql/Dataset.html#withColumn(colName:String,col:org.apache.spark.sql.Column):org.apache.spark.sql.DataFrame), and which is available for all versions of Spark that Deequ builds for.
I ran the same performance test and verified performance is still good:
```
Gathering row-level results
51 columns in row level results
Duration …
```

Fix row-level results implementation for Spark versions <3.3

---

pom.xml

In #545, we were expecting to see breeze 2.1.0 release with spark 3.4+ but Deequ 2.0.7-spark3.4 doesn't seem to include this changes even though the release note mentioned it https://github.com/awslabs/deequ/releases/tag/2.0.7.
Can we backport this change and release it for Deequ 2.0.7-spark3.4 or maybe Deequ 2.0.8?

Backport breeze version upgrade to spark 3.4

---

pom.xml
src/main/scala/com/amazon/deequ/VerificationResult.scala
src/main/scala/com/amazon/deequ/analyzers/CustomAggregator.scala
src/main/scala/com/amazon/deequ/analyzers/CustomSql.scala
src/main/scala/com/amazon/deequ/analyzers/Histogram.scala
src/main/scala/com/amazon/deequ/examples/ConstraintSuggestionExample.scala
src/main/scala/com/amazon/deequ/examples/constraint_suggestion_example.md
src/main/scala/com/amazon/deequ/metrics/Metric.scala
src/main/scala/com/amazon/deequ/suggestions/ConstraintSuggestion.scala
src/main/scala/com/amazon/deequ/suggestions/rules/FractionalCategoricalRangeRule.scala
src/main/scala/com/amazon/deequ/suggestions/rules/RetainCompletenessRule.scala
src/main/scala/com/amazon/deequ/suggestions/rules/interval/ConfidenceIntervalStrategy.scala
src/main/scala/com/amazon/deequ/suggestions/rules/interval/WaldIntervalStrategy.scala
src/main/scala/com/amazon/deequ/suggestions/rules/interval/WilsonScoreIntervalStrategy.scala
src/test/scala/com/amazon/deequ/analyzers/CustomAggregatorTest.scala
src/test/scala/com/amazon/deequ/analyzers/CustomSqlTest.scala
src/test/scala/com/amazon/deequ/suggestions/rules/ConstraintRulesTest.scala
src/test/scala/com/amazon/deequ/suggestions/rules/interval/IntervalStrategyTest.scala

N/A
-  Publishing commits from master to prepare for release.
- Adding commit to update version in pom.xml

Add commits from master branch to release/2.0.8-spark-3.4

---

pom.xml
src/main/scala/com/amazon/deequ/VerificationResult.scala
src/main/scala/com/amazon/deequ/analyzers/CustomAggregator.scala
src/main/scala/com/amazon/deequ/analyzers/CustomSql.scala
src/main/scala/com/amazon/deequ/analyzers/Histogram.scala
src/main/scala/com/amazon/deequ/examples/ConstraintSuggestionExample.scala
src/main/scala/com/amazon/deequ/examples/constraint_suggestion_example.md
src/main/scala/com/amazon/deequ/metrics/Metric.scala
src/main/scala/com/amazon/deequ/suggestions/ConstraintSuggestion.scala
src/main/scala/com/amazon/deequ/suggestions/rules/FractionalCategoricalRangeRule.scala
src/main/scala/com/amazon/deequ/suggestions/rules/RetainCompletenessRule.scala
src/main/scala/com/amazon/deequ/suggestions/rules/interval/ConfidenceIntervalStrategy.scala
src/main/scala/com/amazon/deequ/suggestions/rules/interval/WaldIntervalStrategy.scala
src/main/scala/com/amazon/deequ/suggestions/rules/interval/WilsonScoreIntervalStrategy.scala
src/test/scala/com/amazon/deequ/analyzers/CustomAggregatorTest.scala
src/test/scala/com/amazon/deequ/analyzers/CustomSqlTest.scala
src/test/scala/com/amazon/deequ/suggestions/rules/ConstraintRulesTest.scala
src/test/scala/com/amazon/deequ/suggestions/rules/interval/IntervalStrategyTest.scala

N/A
-  Publishing commits from master to prepare for release.
- Adding commit to update version in pom.xml

Add commits from master branch to release/2.0.8-spark-3.3

---

pom.xml
src/main/scala/com/amazon/deequ/VerificationResult.scala
src/main/scala/com/amazon/deequ/analyzers/CustomAggregator.scala
src/main/scala/com/amazon/deequ/analyzers/CustomSql.scala
src/main/scala/com/amazon/deequ/analyzers/Histogram.scala
src/main/scala/com/amazon/deequ/examples/ConstraintSuggestionExample.scala
src/main/scala/com/amazon/deequ/examples/constraint_suggestion_example.md
src/main/scala/com/amazon/deequ/metrics/Metric.scala
src/main/scala/com/amazon/deequ/suggestions/ConstraintSuggestion.scala
src/main/scala/com/amazon/deequ/suggestions/rules/FractionalCategoricalRangeRule.scala
src/main/scala/com/amazon/deequ/suggestions/rules/RetainCompletenessRule.scala
src/main/scala/com/amazon/deequ/suggestions/rules/interval/ConfidenceIntervalStrategy.scala
src/main/scala/com/amazon/deequ/suggestions/rules/interval/WaldIntervalStrategy.scala
src/main/scala/com/amazon/deequ/suggestions/rules/interval/WilsonScoreIntervalStrategy.scala
src/test/scala/com/amazon/deequ/analyzers/CustomAggregatorTest.scala
src/test/scala/com/amazon/deequ/analyzers/CustomSqlTest.scala
src/test/scala/com/amazon/deequ/suggestions/rules/ConstraintRulesTest.scala
src/test/scala/com/amazon/deequ/suggestions/rules/interval/IntervalStrategyTest.scala

N/A
-  Publishing commits from master to prepare for release.
- Adding commit to update version in pom.xml

Add commits from master branch to release/2.0.8-spark-3.2

---

src/main/scala/com/amazon/deequ/VerificationResult.scala
src/test/scala/com/amazon/deequ/VerificationSuiteTest.scala

- When a check fails due to a precondition failure, the row level results are not evaluated correctly.
- For example, let's say a check has a completeness constraint which passes, and a minimum constraint which fails due to a precondition failure.
- The row level results will be the results for just the completeness constraint. There will be no results generated for the minimum constraint, and therefore the row level results will be incorrect.
- We fix this by adding a default outcome for when the row level result column is not provided by the analyzer.

Fix row level bug when composing outcome

---

src/main/scala/com/amazon/deequ/checks/Check.scala
src/test/scala/com/amazon/deequ/VerificationSuiteTest.scala
src/test/scala/com/amazon/deequ/checks/CheckTest.scala

- Add `areUnique` check, similar to the [`areComplete`](https://github.com/awslabs/deequ/blob/82537bd832c731e0730025f781bee2e9682f3637/src/main/scala/com/amazon/deequ/checks/Check.scala#L177-L182) check to check for the uniqueness of multiple columns
- Added unit tests in the CheckTests and VerificationSuiteTests

Are unique check

---

src/test/scala/com/amazon/deequ/VerificationSuiteTest.scala

* Adds a test to verify that Deequ's isContainedIn constraint correctly handles string values containing single quotes in the verification process.

Adds a test to verify that Deequ's isContainedIn constraint correctly handles string values containing single quotes in the verification process.

---

pom.xml
src/test/scala/com/amazon/deequ/dqdl/ParserTest.scala

Add dependency to Glue Data Quality Definition Language Parser. (DQDL Parser)
This change enables the use of DQ rulesets.
More info about the parser https://github.com/awslabs/dqdl
DQDL Reference: https://docs.aws.amazon.com/glue/latest/dg/dqdl.html

add DQDL parser dependency

---

src/main/scala/com/amazon/deequ/repository/AnalysisResultSerde.scala
src/test/scala/com/amazon/deequ/repository/AnalysisResultSerdeTest.scala

*Issue #, if available:* #596 
This PR addresses a discrepancy when using a `FileSystemMetricsRepository` with an `Analyzer` that has `analyzerOptions` set.
Given an analyzer which has `analyzerOptions` configured:
```
Compliance("rule1", "att1 > 3", columns = List("att1"),
analyzerOptions = Some(AnalyzerOptions(
nullBehavior = NullBehavior.Ignore,
filteredRow = FilteredRowOutcome.NULL
))
)
```
Because the `FileSystemMetricsRepository.get()` function [compares the entire analyzer object](https://github.com/awslabs/deequ/blob/310699b434d413f8f07ccf54d6eff9bc4de35e58/src/main/scala/com/amazon/deequ/repository/fs/FileSystemMetricsRepository.scala#L154), it fails to match the current analyzer (with `analyzerOptions`) to any historical metric analyzer.
This issue …

Add AnalyzerOptions to Analyzer serialize / deserialize logic

---

src/main/scala/com/amazon/deequ/analyzers/runners/AnalysisRunner.scala
src/test/scala/com/amazon/deequ/analyzers/runners/AnalysisRunnerTests.scala

#600 
This PR optimizes the use of Size() metrics in AnalysisRunner to avoid redundant 
Spark scans when obtaining the row count for grouping analyzers. 
Specifically:
- Adds a conditional check to include Size(None) only when:
1) Grouping analyzers require a global row count (i.e., not a FrequencyBasedAnalyzer).
2) We haven't already included Size(None) implicitly.
3) There's at least one analyzer whose state isn't already loaded (so an actual scan is needed).
- Introduces a helper method `actuallyNeedsScanning` to detect whether all 
required analyzer states are already available from `aggregateWith`. If so, we can skip a new scan entirely.
- Extracts the row count from the Size() metric only if it was actually included in the scanning …

Refine row count retrieval to skip redundant Size() scans

---

src/main/scala/com/amazon/deequ/analyzers/Histogram.scala
src/test/scala/com/amazon/deequ/analyzers/DistributionTest.scala

*Issue #, if available:* Distribution changes.
*Description of changes:* Distributions consist of 1/ histograms (binned ranges) and 2/ value distributions (categorical). The current deequ implementation only supports the latter currently. This PR makes a small change to make those in descending frequency order. Following PRs will implement histograms with binned ranges.

Modify Histogram to be in descending frequency

---

src/main/scala/com/amazon/deequ/analyzers/Histogram.scala
src/main/scala/com/amazon/deequ/analyzers/HistogramBase.scala

*Description of changes:* Distributions consist of 1/ histograms (binned ranges) and 2/ value distributions (categorical). The current deequ implementation only supports the latter. This PR pulls the shared distribution functionality and puts that in a `HistogramBase.scala`. A new class will be added for the binned histogram implementation.

Introduce HistogramBase for common histogram behavior

---

src/main/scala/com/amazon/deequ/checks/Check.scala
src/main/scala/com/amazon/deequ/constraints/Constraint.scala
src/main/scala/com/amazon/deequ/dqdl/translation/DQDLRuleTranslator.scala
src/main/scala/com/amazon/deequ/dqdl/translation/rules/CustomSqlRule.scala
src/test/scala/com/amazon/deequ/checks/CustomSqlCheckTest.scala
src/test/scala/com/amazon/deequ/dqdl/EvaluateDataQualitySpec.scala
src/test/scala/com/amazon/deequ/dqdl/translation/DQDLRuleTranslatorSpec.scala

Introduce a CustomSql validation capability to Deequ via:
- A new **Deequ CustomSql check** leveraging the CustomSql analyzer
- A new DQDL rule: **CustomSql** which utilizes the **Deequ CustomSql check** from above.
- Implements the CustomSql check to allow arbitrary SQL-based data quality checks.
- Adds a test suite covering the new CustomSql check functionality.
- Integrates the CustomSql rule into the DQDL engine, enabling DQDL Custom SQL-based rule definitions.
CustomSql rule support expands Deequ’s flexibility - users can now define custom validation logic with SQL, making ad-hoc or complex checks far easier to express.
---

Add support for DQDL CustomSql rule & Deequ CustomSql check

---

README.md
src/main/scala/com/amazon/deequ/dqdl/translation/DQDLRuleTranslator.scala
src/main/scala/com/amazon/deequ/dqdl/translation/rules/IsPrimaryKeyRule.scala
src/test/scala/com/amazon/deequ/dqdl/EvaluateDataQualitySpec.scala

Add support for DQDL rule: IsPrimaryKey, allowing users to enforce primary key-like uniqueness and non-null constraints on selected columns

Add support for DQDL IsPrimaryKey rule

---

README.md
src/main/scala/com/amazon/deequ/analyzers/ColumnExists.scala
src/main/scala/com/amazon/deequ/checks/Check.scala
src/main/scala/com/amazon/deequ/constraints/Constraint.scala
src/main/scala/com/amazon/deequ/dqdl/translation/DQDLRuleTranslator.scala
src/main/scala/com/amazon/deequ/dqdl/translation/rules/ColumnExistsRule.scala
src/test/scala/com/amazon/deequ/dqdl/EvaluateDataQualitySpec.scala
src/test/scala/com/amazon/deequ/examples/ScalaDQDLExample.scala

Added ColumnExists
- Analyzer / Constraint / Check
- DQDL implementation
- Unit Test
From
- https://docs.aws.amazon.com/glue/latest/dg/dqdl-rule-types-ColumnExists.html
*new*
ColumnExists now outputs a metric!
```
Rules=[ColumnExists \"sampom\"]
Dataset.sampom.ColumnExists -> 1.0
```

Add ColumnExists Check, Constraint, and DQDL Rule

---

.travis.yml
README.md

Travis CI was deprecated a long time ago, also removed the leftover Travis CI config file.

Replace Travis CI badge with Github Actions Badge

---

src/main/scala/com/amazon/deequ/analyzers/HistogramBinned.scala
src/test/scala/com/amazon/deequ/analyzers/HistogramBinnedTest.scala
src/test/scala/com/amazon/deequ/constraints/ConstraintsTest.scala

Count null bins (similar to existing `Histogram` implementation) and empty bins. Counting empty bins is proper behavior. Counting null bins is a design choice, but maintaining what is already in place by `Histogram`.
- `HistogramBinnedTest.scala` unit tests verifies this behavior (was failing previously).
- The existing test "handle all null data gracefully" checked the null bin was already counted.
- `ConstraintsTest.scala` was modified because the empty bins need to be included in the total bin count. 

HistogramBinned should count empty and null bins in total
