- README.md
- src/main/scala/com/amazon/deequ/examples/BasicExample.scala
- src/main/scala/com/amazon/deequ/examples/ExampleUtils.scala
- src/main/scala/com/amazon/deequ/examples/IncrementalMetricsExample.scala
- src/main/scala/com/amazon/deequ/examples/Item.scala
- src/test/scala/com/amazon/deequ/examples/ExamplesTest.scala
Added an example for the stateful incremental metrics computation
> Example for incremental metrics computation

- README.md
Added the code for using our release candidate via maven.
> Announce 1.0.0-rc0 README.md

- README.md
- pom.xml
- src/main/scala/com/amazon/deequ/examples/MetricsRepositoryExample.scala
- src/main/scala/com/amazon/deequ/repository/fs/FileSystemMetricsRepository.scala
- src/test/scala/com/amazon/deequ/examples/ExamplesTest.scala
*Issue #8:*
Example for using the metrics repository.
> Example for storing metrics in a repository

- src/main/scala/com/amazon/deequ/examples/BasicExample.scala
- src/main/scala/com/amazon/deequ/examples/ExampleUtils.scala
- src/main/scala/com/amazon/deequ/examples/IncrementalMetricsExample.scala
- src/main/scala/com/amazon/deequ/examples/MetricsRepositoryExample.scala
- src/main/scala/com/amazon/deequ/examples/UpdateMetricsOnPartitionedDataExample.scala
- src/main/scala/com/amazon/deequ/examples/entities.scala
- src/test/scala/com/amazon/deequ/examples/ExamplesTest.scala
*Issue #18 *
Example for updating metrics of partitioned data.
> Draft for examples for states on partitioned data

- README.md
- src/main/scala/com/amazon/deequ/examples/algebraic_states_example.md
> Add markdown documention for the algebraic state example

- README.md
- pom.xml
- src/main/scala/com/amazon/deequ/examples/AnomalyDetectionExample.scala
- src/main/scala/com/amazon/deequ/examples/DataProfilingExample.scala
- src/main/scala/com/amazon/deequ/examples/anomaly_detection_example.md
- src/test/scala/com/amazon/deequ/examples/ExamplesTest.scala
> Example for anomaly detection

- README.md
- src/main/scala/com/amazon/deequ/examples/ConstraintSuggestionExample.scala
- src/main/scala/com/amazon/deequ/examples/constraint_suggestion_example.md
- src/test/scala/com/amazon/deequ/examples/ExamplesTest.scala
> Example for constraint suggestion

- src/main/scala/com/amazon/deequ/profiles/ColumnProfiler.scala
- src/test/scala/com/amazon/deequ/profiles/ColumnProfilerTest.scala
- src/test/scala/com/amazon/deequ/utils/FixtureSupport.scala
> Histograms for boolean columns #59

- README.md
> Fix little coding typo in the README

- src/main/scala/com/amazon/deequ/checks/Check.scala
> fix typo in non-negative constraint

- src/main/scala/com/amazon/deequ/analyzers/ApproxCountDistinct.scala
- src/main/scala/com/amazon/deequ/analyzers/StateProvider.scala
- src/main/scala/com/amazon/deequ/analyzers/catalyst/StatefulHyperloglogPlus.scala
> Rename HLL Utils

- src/main/scala/com/amazon/deequ/examples/constraint_suggestion_example.md
Addition to PR https://github.com/awslabs/deequ/pull/66
> remove isPositive constraint suggestion

- src/main/scala/com/amazon/deequ/analyzers/applicability/Applicability.scala
- src/test/scala/com/amazon/deequ/checks/ApplicabilityTest.scala
- src/test/scala/com/amazon/deequ/checks/FilterableCheckTest.scala
> applicability for byte, short and long data types

- README.md
*Issue #, if available:* none
Fixes documentation (code examples)
> Added imports, fixed inconsistencies in code snippets

- src/test/scala/com/amazon/deequ/analyzers/AnalyzerTests.scala
Test for https://github.com/awslabs/deequ/issues/95
> Histograms on numeric columns

- README.md
- src/main/scala/com/amazon/deequ/examples/BasicExample.scala
An example on the README checks for equality incorrectly, and its matching BasicExample could be more clear. 
Fixed sample logic and unified example with README.
> Update README, fix and clarify types in example constraint test.

- src/main/scala/com/amazon/deequ/examples/data_profiling_example.md
> data_profiling_example.md

- src/main/scala/com/amazon/deequ/analyzers/StateProvider.scala
- src/test/scala/com/amazon/deequ/analyzers/StateProviderTest.scala
*Issue #151*
*Description of changes: Added if-else based on allowOverwrite i.e if allowOverwrite = true, then  SaveMode.Overwrite otherwise SaveMode.ErrorIfExists for storing frequency based states on DFS*
> Fix allow overwrite functionality for storing frequency based states

- src/main/scala/com/amazon/deequ/analyzers/KLLSketch.scala
- src/main/scala/com/amazon/deequ/checks/Check.scala
- src/main/scala/com/amazon/deequ/constraints/Constraint.scala
- src/main/scala/com/amazon/deequ/examples/KLLCheckExample.scala
- src/main/scala/com/amazon/deequ/examples/KLLExample.scala
- src/main/scala/com/amazon/deequ/profiles/ColumnProfiler.scala
- src/main/scala/com/amazon/deequ/profiles/ColumnProfilerRunBuilder.scala
- src/main/scala/com/amazon/deequ/profiles/ColumnProfilerRunner.scala
- src/main/scala/com/amazon/deequ/suggestions/ConstraintSuggestionRunBuilder.scala
- src/main/scala/com/amazon/deequ/suggestions/ConstraintSuggestionRunner.scala
- src/test/scala/com/amazon/deequ/profiles/KLLProfileTest.scala
*Issue #, if available:* The distance computation is yet to be implemented, and more unit testing is required.
*Description of changes:*  Make KLL Sketches parameters configurable & serialize to analysis files.
> Kll features

- src/main/scala/com/amazon/deequ/analyzers/Distance.scala
- src/main/scala/com/amazon/deequ/profiles/ColumnProfile.scala
- src/test/scala/com/amazon/deequ/KLL/KLLDistanceTest.scala
Previously we use Categorial case class for distance computation, now change that to mutable map.
> Change categorical data structure to map

- pom.xml
- src/main/scala/com/amazon/deequ/analyzers/Analyzer.scala
- src/main/scala/com/amazon/deequ/analyzers/KLLSketch.scala
- src/main/scala/com/amazon/deequ/analyzers/QuantileNonSample.scala
- src/main/scala/com/amazon/deequ/analyzers/runners/AnalysisRunner.scala
- src/main/scala/com/amazon/deequ/analyzers/runners/KLLRunner.scala
- src/main/scala/com/amazon/deequ/examples/KLLExample.scala
- src/main/scala/com/amazon/deequ/metrics/KLLMetric.scala
- src/main/scala/com/amazon/deequ/profiles/ColumnProfile.scala
- src/main/scala/com/amazon/deequ/profiles/ColumnProfiler.scala
- src/test/scala/com/amazon/deequ/KLL/KLLBenchmark.java
- src/test/scala/com/amazon/deequ/KLL/KLLBenchmarkHelper.scala
- src/test/scala/com/amazon/deequ/profiles/ColumnProfilerRunnerTest.scala
- src/test/scala/com/amazon/deequ/suggestions/ConstraintSuggestionRunnerTest.scala
Adds a benchmark for the KLL Sketch
> KLL Sketch Optimisations

- src/main/scala/com/amazon/deequ/repository/AnalysisResultSerde.scala
- src/test/scala/com/amazon/deequ/repository/AnalysisResultSerdeTest.scala
This PR fixes some problems caused by missing Min/MaxLength analyzers in AnalysisResultSerde.
> Adds Min/MaxLength analyzers in repository/AnalysisResultSerde.

- src/main/scala/com/amazon/deequ/analyzers/runners/AnalysisRunner.scala
- src/test/scala/com/amazon/deequ/analyzers/StateProviderTest.scala
*Issue #210 
*Description of changes:* Ability to save states and aggregate for other metrics, found issue with Histogram analyzer
> Save and aggregate states for other metrics

- src/main/scala/com/amazon/deequ/analyzers/Analyzer.scala
- src/main/scala/com/amazon/deequ/analyzers/Completeness.scala
- src/main/scala/com/amazon/deequ/analyzers/DataType.scala
- src/main/scala/com/amazon/deequ/analyzers/GroupingAnalyzers.scala
- src/main/scala/com/amazon/deequ/analyzers/PatternMatch.scala
- src/test/scala/com/amazon/deequ/analyzers/AnalyzerTests.scala
- src/test/scala/com/amazon/deequ/utils/FixtureSupport.scala
Adds additional preconditions to check for nested columns #201 
> Additional preconditions to check for nested columns

- src/main/scala/com/amazon/deequ/examples/data_profiling_example.md
Change-Id: I2ae6cc2474b14ef2340078e4e9edf211b21fd389
> Typo in loop over profiles

- CONTRIBUTING.md
- docs/key-concepts.md
- Ref https://github.com/awslabs/deequ/issues/41
https://github.com/awslabs/deequ/issues/41
Some initial documentation on key concepts in the codebase. I figured worth putting forward even though it's light, as it may still be a helpful start.
> Add documentation on key concepts within the code

- pom.xml
*Issue #, if available:* n/a
Upgrading Spark dependency to 2.3.3
> Upgrades Spark version from 2.2.2 to 2.3.3

- README.md
The team behind PyDeequ has asked us to reference their package from deequ. This PR adds links to the PyDeequ repository, documentation, and PyPI page to our readme.
> mention PyDeequ in README

- README.md
- settings.xml
- This PR updates the install instructions in the README to reflect that we now publish [one release per spark-scala version combination](https://repo1.maven.org/maven2/com/amazon/deequ/deequ/).
- The PR also adds the file `settings.xml` that is needed to publish maven releases. 
> Update readme install instructions, add settings.xml

- src/main/scala/com/amazon/deequ/VerificationRunBuilder.scala
- src/main/scala/com/amazon/deequ/analyzers/runners/AnalysisRunBuilder.scala
- src/main/scala/com/amazon/deequ/profiles/ColumnProfilerRunBuilder.scala
The previous implementations are just unfunctional we didn't use the user-specified argument, 
but just kept the default fallback value.
> fix overwrite option passings

- README.md
The maven artifact had a typo in the README
> update maven dependency in the README

- CONTRIBUTING.md
- README.md
- docs/key-concepts.md
- src/main/scala/com/amazon/deequ/examples/algebraic_states_example.md
- src/main/scala/com/amazon/deequ/examples/anomaly_detection_example.md
- src/main/scala/com/amazon/deequ/examples/constraint_suggestion_example.md
* fixed formatting of the nested lists
* fixed some typos
* fixed some grammar
> fix list markup, fix typos, some adjustments in grammar

- src/main/scala/com/amazon/deequ/suggestions/rules/CategoricalRangeRule.scala
- src/main/scala/com/amazon/deequ/suggestions/rules/FractionalCategoricalRangeRule.scala
- sort suggested categorical values when generating constraint code (sort in lexical order)
- this may improve the readability of suggested constraints and help one refer to it as some form of the data schema
> sort suggested categories

- .github/workflows/maven.yml
*Issue #, if available:* N/A
Configured a Github action to build master branch against PRs.
*Testing Evidence:*
- https://github.com/rdsharma26/deequ/actions/runs/3988489667
> Add Github build action

- pom.xml
Quick PR to update version in `pom.xml`
> Update version to 2.0.3-spark-3.3

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/ISSUE_TEMPLATE/general-inquiry.md
Adding issue templates to better organize incoming issues.
- Bug Report
- Feature Request
- General Inquiry
> Update issue templates

- src/main/scala/com/amazon/deequ/analyzers/Analyzer.scala
- src/main/scala/com/amazon/deequ/analyzers/Correlation.scala
- src/main/scala/com/amazon/deequ/analyzers/MutualInformation.scala
- src/main/scala/com/amazon/deequ/metrics/Metric.scala
- src/test/scala/com/amazon/deequ/VerificationResultTest.scala
- src/test/scala/com/amazon/deequ/VerificationSuiteTest.scala
- src/test/scala/com/amazon/deequ/analyzers/AnalysisTest.scala
- src/test/scala/com/amazon/deequ/analyzers/AnalyzerTests.scala
- src/test/scala/com/amazon/deequ/analyzers/runners/AnalyzerContextTest.scala
- src/test/scala/com/amazon/deequ/repository/AnalysisResultSerdeTest.scala
- src/test/scala/com/amazon/deequ/repository/AnalysisResultTest.scala
- src/test/scala/com/amazon/deequ/repository/MetricsRepositoryMultipleResultsLoaderTest.scala
- src/test/scala/com/amazon/deequ/repository/fs/FileSystemMetricsRepositoryTest.scala
- src/test/scala/com/amazon/deequ/repository/memory/InMemoryMetricsRepositoryTest.scala
> Fix typo Mutlicolumn -> Multicolumn

- src/main/scala/com/amazon/deequ/analyzers/Analyzer.scala
- src/main/scala/com/amazon/deequ/analyzers/Compliance.scala
- src/main/scala/com/amazon/deequ/analyzers/MaxLength.scala
- src/main/scala/com/amazon/deequ/analyzers/Maximum.scala
- src/main/scala/com/amazon/deequ/analyzers/MinLength.scala
- src/main/scala/com/amazon/deequ/analyzers/Minimum.scala
- src/main/scala/com/amazon/deequ/analyzers/PatternMatch.scala
- src/main/scala/com/amazon/deequ/checks/Check.scala
- src/main/scala/com/amazon/deequ/constraints/Constraint.scala
- src/test/scala/com/amazon/deequ/VerificationSuiteTest.scala
- src/test/scala/com/amazon/deequ/analyzers/AnalysisTest.scala
- src/test/scala/com/amazon/deequ/analyzers/AnalyzerTests.scala
- src/test/scala/com/amazon/deequ/analyzers/ComplianceTest.scala
- src/test/scala/com/amazon/deequ/analyzers/MaxLengthTest.scala
- src/test/scala/com/amazon/deequ/analyzers/MaximumTest.scala
- src/test/scala/com/amazon/deequ/analyzers/MinLengthTest.scala
- src/test/scala/com/amazon/deequ/analyzers/MinimumTest.scala
- src/test/scala/com/amazon/deequ/analyzers/PatternMatchTest.scala
- src/test/scala/com/amazon/deequ/analyzers/StateProviderTest.scala
- src/test/scala/com/amazon/deequ/repository/AnalysisResultSerdeTest.scala
- src/test/scala/com/amazon/deequ/utils/FixtureSupport.scala
Add Max, Min, PatternMatch to rowlevel results
Change the null behavior back
> Added ColumnValues to Row-level Results

- src/main/scala/com/amazon/deequ/suggestions/ConstraintSuggestionRunner.scala
- src/test/scala/com/amazon/deequ/suggestions/ConstraintSuggestionsIntegrationTest.scala
- Updated the test which was adding the uniqueness suggestion. The addition is no longer required in that test since the EXTENTED list now contains the uniqueness suggestion.
> Added Uniqueness constraint suggestion to the list of EXTENDED suggestions

- pom.xml
https://github.com/awslabs/deequ/issues/481 
- Add Spark 3.4 support 
`mvn clean package` run successfully on my local machine. Test result is as followed:
```
Run completed in 4 minutes, 56 seconds.
Total number of tests run: 552
Suites: completed 64, aborted 0
Tests: succeeded 552, failed 0, canceled 0, ignored 0, pending 0
All tests passed.
```
> Add Spark 3.4 support

- pom.xml
Update minor version to 2.0.5 for Spark 3.4 maven release
> Update minor version for Spark 3.4 maven release

- pom.xml
> Updating release version in pom.xml

- pom.xml
- Updated version in pom.xml to 2.0.7-spark-3.2
> Updated version in pom.xml to 2.0.7-spark-3.2

- pom.xml
- Updated version in pom.xml to 2.0.7-spark-3.3
> Updated version in pom.xml to 2.0.7-spark-3.3

- pom.xml
- Updated version in pom.xml to 2.0.7-spark-3.4
> Updated version in pom.xml to 2.0.7-spark-3.4

- pom.xml
- Updated version in pom.xml to 2.0.7-spark-3.5
> Updated version in pom.xml to 2.0.8-spark-3.5

- pom.xml
> Update Breeze version for spark 3.3

- pom.xml
- src/main/scala/com/amazon/deequ/VerificationResult.scala
- src/main/scala/com/amazon/deequ/analyzers/Histogram.scala
N/A
Publishing commits from master to prepare for release.
> Add commits from master branch to release/2.0.8-spark-3.5

- pom.xml
- src/main/scala/com/amazon/deequ/VerificationResult.scala
- src/main/scala/com/amazon/deequ/analyzers/CustomAggregator.scala
- src/main/scala/com/amazon/deequ/analyzers/CustomSql.scala
- src/main/scala/com/amazon/deequ/analyzers/Histogram.scala
- src/main/scala/com/amazon/deequ/examples/ConstraintSuggestionExample.scala
- src/main/scala/com/amazon/deequ/examples/constraint_suggestion_example.md
- src/main/scala/com/amazon/deequ/metrics/Metric.scala
- src/main/scala/com/amazon/deequ/suggestions/ConstraintSuggestion.scala
- src/main/scala/com/amazon/deequ/suggestions/rules/FractionalCategoricalRangeRule.scala
- src/main/scala/com/amazon/deequ/suggestions/rules/RetainCompletenessRule.scala
- src/main/scala/com/amazon/deequ/suggestions/rules/interval/ConfidenceIntervalStrategy.scala
- src/main/scala/com/amazon/deequ/suggestions/rules/interval/WaldIntervalStrategy.scala
- src/main/scala/com/amazon/deequ/suggestions/rules/interval/WilsonScoreIntervalStrategy.scala
- src/test/scala/com/amazon/deequ/analyzers/CustomAggregatorTest.scala
- src/test/scala/com/amazon/deequ/analyzers/CustomSqlTest.scala
- src/test/scala/com/amazon/deequ/suggestions/rules/ConstraintRulesTest.scala
- src/test/scala/com/amazon/deequ/suggestions/rules/interval/IntervalStrategyTest.scala
N/A
-  Publishing commits from master to prepare for release.
- Adding commit to update version in pom.xml
> Add commits from master branch to release/2.0.8-spark-3.1

- src/main/scala/com/amazon/deequ/VerificationResult.scala
- src/main/scala/com/amazon/deequ/analyzers/CustomAggregator.scala
- src/main/scala/com/amazon/deequ/analyzers/Histogram.scala
- src/main/scala/com/amazon/deequ/examples/ConstraintSuggestionExample.scala
- src/main/scala/com/amazon/deequ/examples/constraint_suggestion_example.md
- src/main/scala/com/amazon/deequ/metrics/Metric.scala
- src/main/scala/com/amazon/deequ/suggestions/ConstraintSuggestion.scala
- src/main/scala/com/amazon/deequ/suggestions/rules/FractionalCategoricalRangeRule.scala
- src/main/scala/com/amazon/deequ/suggestions/rules/RetainCompletenessRule.scala
- src/main/scala/com/amazon/deequ/suggestions/rules/interval/ConfidenceIntervalStrategy.scala
- src/main/scala/com/amazon/deequ/suggestions/rules/interval/WaldIntervalStrategy.scala
- src/main/scala/com/amazon/deequ/suggestions/rules/interval/WilsonScoreIntervalStrategy.scala
- src/test/scala/com/amazon/deequ/VerificationSuiteTest.scala
- src/test/scala/com/amazon/deequ/analyzers/CustomAggregatorTest.scala
- src/test/scala/com/amazon/deequ/suggestions/rules/ConstraintRulesTest.scala
- src/test/scala/com/amazon/deequ/suggestions/rules/interval/IntervalStrategyTest.scala
Cherry-pick from spark3.3 to spark3.1
> Cherry-pick from spark3.3 to spark3.1

- pom.xml
- Updated version in pom.xml to 2.0.9-spark-3.1
> Updated version in pom.xml to 2.0.9-spark-3.1

- pom.xml
- Updated version in pom.xml to 2.0.9-spark-3.2
> Updated version in pom.xml to 2.0.9-spark-3.2

- pom.xml
- Updated version in pom.xml to 2.0.9-spark-3.4
> Release/2.0.9 spark 3.4

- pom.xml
- Updated version in pom.xml to 2.0.10-spark-3.3
> Release/2.0.10 spark 3.3

- pom.xml
- Updated version in pom.xml to 2.0.11-spark-3.5
> Updated version in pom.xml to 2.0.11-spark-3.5

- pom.xml
- Updated version in pom.xml to 2.0.11-spark-3.4
> Updated version in pom.xml to 2.0.11-spark-3.4

- src/main/scala/com/amazon/deequ/dqdl/translation/DQDLRuleTranslator.scala
- src/main/scala/com/amazon/deequ/dqdl/translation/rules/ColumnCorrelationRule.scala
- src/main/scala/com/amazon/deequ/dqdl/translation/rules/CompletenessRule.scala
- src/main/scala/com/amazon/deequ/dqdl/translation/rules/IsCompleteRule.scala
- src/main/scala/com/amazon/deequ/dqdl/translation/rules/IsUniqueRule.scala
- src/main/scala/com/amazon/deequ/dqdl/translation/rules/UniquenessRule.scala
- src/test/scala/com/amazon/deequ/dqdl/EvaluateDataQualitySpec.scala
- src/test/scala/com/amazon/deequ/dqdl/translation/DQDLRuleTranslatorSpec.scala
Add implementation for the following DQDL(Data Quality Definition Language) rules:
1. CompletenessRule, 
2. IsCompleteRule, 
3. UniquenessRule, 
4. IsUniqueRule, 
5. ColumnCorrelationRule
> Add implementation for DQDL rules: CompletenessRule, IsCompleteRule, UniquenessRule, IsUniqueRule, ColumnCorrelationRule

- src/main/scala/com/amazon/deequ/repository/AnalysisResultSerde.scala
- src/test/scala/com/amazon/deequ/repository/AnalysisResultSerdeTest.scala
Thank you for this wonderful library :)
---
*Issue #, if available:* [#627](https://github.com/awslabs/deequ/issues/627)
- Add a SerDe implementation of KLLSketch which was missing.
I validated the new testcase succeeds:
```bash
mvn test -Dsuites=com.amazon.deequ.repository.AnalysisResultSerdeTest
```
And a failing test I had written also succeeds:
---
> fix(kll): Add SerDe Implementation for KLLSketch

- README.md
- src/main/scala/com/amazon/deequ/dqdl/translation/DQDLRuleTranslator.scala
- src/main/scala/com/amazon/deequ/dqdl/translation/rules/ColumnLengthRule.scala
- src/main/scala/com/amazon/deequ/dqdl/util/DQDLUtility.scala
- src/test/scala/com/amazon/deequ/dqdl/EvaluateDataQualitySpec.scala
- src/test/scala/com/amazon/deequ/dqdl/translation/DQDLRuleTranslatorSpec.scala
- src/test/scala/com/amazon/deequ/dqdl/translation/rules/ColumnLengthRuleSpec.scala
- src/test/scala/com/amazon/deequ/utils/ConditionUtils.scala
- Add support for DQDL rule: ColumnLength, allowing users to enforce checks on the length of string columns
> Add support for DQDL ColumnLength rule

- pom.xml
- Updated version in pom.xml to 2.0.12-spark-3.5
> Updated version in pom.xml to 2.0.12-spark-3.5

- src/main/scala/com/amazon/deequ/repository/fs/FileSystemMetricsRepository.scala
#625 
* Load allResults from File System once and use it for all subsequent filtering based on filters in `get()` instead of loading results every time for each metric anomaly detection
* Update allResults in `save()` method to have new results
*Testing*
* `FileSystemMetricsRepositoryTest` all test cases passed ✅ 
* `mvn clean install` is successful ✅ 
> Optimize loading all results in FileSystemMetricRepository
